spring:
  datasource:
    url: jdbc:mysql://localhost:3306/movie_inventory?useSSL=false
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  kafka:
    bootstrap-servers: localhost:20010
    admin:
      client-id: movie-schedule-rest-api

server:
  port: 8082
  servlet:
    context-path: /movie-inventory-api
logging:
  file:
    name: D:/Development/WS/log/local/movie-inventory-api/movie-inventory-api.log
  pattern:
    console: "%d %-5level %logger : %msg%n"
    file: "%d %-5level [%thread] %logger : %msg%n"
  level:
    org.springframework: INFO
    org.hibernate: INFO
    org.example.movie.inventory: INFO
    org.springframework.web: TRACE
    org.springframework.security: TRACE
    org.springframework.security.oauth2: TRACE

kafka:
  movieBookingApi:
    groupName: movie-schedule
    movieInventory:
      topic:
        request: movie-inventory-request
        response: movie-inventory-response
        serialization-class: org.example.movie.core.common.schedule.MovieInventoryRequest
    movieDetails:
      topic:
        request: movie-details-request
        response: movie-details-response
        serialization-class: org.example.movie.core.common.schedule.MovieDetailsListResponse
